Add bazel patch to work around underdefined dependency
Fixes https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2824#0185bd7e-6fed-4c16-ad52-256b600d4ae3 for now. Updating bazel requires more work because of third party dependencies:

```
ERROR: /private/var/tmp/_bazel_ksmiley/430ca27aaa11819957cd32dd0f9637d8/external/io_bazel/third_party/BUILD:464:13: no such package '@maven//': The repository '@maven' could not be resolved: Repository '@maven' is not defined and referenced by '@io_bazel//third_party:guava'
```